import { Playfair_Display, Noto_Sans } from "next/font/google";
import "./globals.css";

const playfair_Display = Playfair_Display({ subsets: ["latin"], variable: "--playfairDisplay" });
const noto_Sans = Noto_Sans({ subsets: ["latin"], variable: "--notoSans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair_Display.variable} ${noto_Sans.variable}`}>{children}</body>
    </html>
  );
}
