import { Playfair_Display, Noto_Sans } from "next/font/google";
import "./globals.css";
import { fetchData } from "@/utils/fetchData";

const playfair_Display = Playfair_Display({
  subsets: ["latin"],
  variable: "--playfairDisplay",
});
const noto_Sans = Noto_Sans({ subsets: ["latin"], variable: "--notoSans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const colors = await fetchData(
    "https://9n04icih.api.sanity.io/v2022-03-07/data/query/production?query=*%5B_type+%3D%3D+%22homePage%22%5D%5B0%5D%7B%0A++bgColor%2CTxtColor+%0A%7D"
  );

  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: `${colors.bgColor} !important`,
          color: `${colors.TxtColor} !important`,
        }}
        className={`${playfair_Display.variable} ${noto_Sans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
